

name: build-ctrlblock-dev
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@main
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 21
            - name: Build extension
              run: |
                set -x
                export CTRLBLOCK_DEPLOY_TOKEN=${{ secrets.CTRLBLOCK_DEPLOY_TOKEN }}
                export GIT_SHA=$(git rev-parse --short HEAD)
                npm install -g sass
                npm install
                npm run build
            - name: Upload build
              uses: actions/upload-artifact@v4
              with:
                  name: ctrlblock-${{ github.sha }}
                  path: dist/
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/download-artifact@v4
          with:
            name: ctrlblock-${{ github.sha }}
            path: dist/
        - name: Upload to CWS
          run: |
            cd dist/; zip -r ctrlblock-${{ github.sha }}.zip ./; cd ..
            CWS_UPLOAD_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" \
            -d "grant_type=refresh_token" \
            -d "client_id=${{ secrets.CWS_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.CWS_CLIENT_SECRET }}" \
            -d "refresh_token=${{ secrets.CWS_REFRESH_TOKEN }}" | \
            sed -n -r -e 's/.*"access_token": "([^"]+)",$/\1/p')
            curl \
            -H "Authorization: Bearer $CWS_UPLOAD_TOKEN"  \
            -H "x-goog-api-version: 2" \
            -X PUT \
            -T dist/ctrlblock-${{ github.sha }}.zip \
            https://www.googleapis.com/upload/chromewebstore/v1.1/items/${{ secrets.CWS_EXTENSION_ID }}
